import type { IndicatorSet } from '../../core/types';
import { BUILTIN } from '../shared';

const ADDED_AT = '2026-09-29';
const CORNER_SEED = 1;

/** The ten Arcade sets: tiny self-playing games whose wins and losses are the success and error states. */
export const ARCADE_SETS = [
  {
    id: 'stack-clear',
    name: 'Stack and Clear',
    description:
      'Blocks fall, slide into place, complete two rows and blink away, the satisfaction of a line clear.',
    intent: 'loading',
    cols: 6,
    rows: 8,
    states: {
      idle: { kind: 'recipe', recipe: 'arcade', params: { variant: 'stack-rest' } },
      thinking: { kind: 'recipe', recipe: 'arcade', params: { variant: 'stack' } },
      progress: { kind: 'recipe', recipe: 'arcade', params: { variant: 'stack-progress' } },
      success: { kind: 'recipe', recipe: 'arcade', params: { variant: 'stack-done' } },
      error: { kind: 'recipe', recipe: 'arcade', params: { variant: 'stack-topout' } },
    },
    transition: 'cut',
    tags: ['blocks', 'arcade', 'build', 'deploy'],
    contexts: ['card', 'page', 'splash', 'terminal'],
    collections: ['arcade'],
    addedAt: ADDED_AT,
    ...BUILTIN,
  },
  {
    id: 'rally',
    name: 'Paddle Rally',
    description:
      'Two paddles return a ball back and forth on their own, one sliding just in time to meet it.',
    intent: 'thinking',
    cols: 9,
    rows: 5,
    states: {
      idle: { kind: 'recipe', recipe: 'arcade', params: { variant: 'rally-serve' } },
      thinking: { kind: 'recipe', recipe: 'arcade', params: { variant: 'rally' } },
      waiting: { kind: 'recipe', recipe: 'arcade', params: { variant: 'rally-wait' } },
      success: { kind: 'recipe', recipe: 'arcade', params: { variant: 'rally-rest' } },
      error: { kind: 'recipe', recipe: 'arcade', params: { variant: 'rally-miss' } },
    },
    transition: 'cut',
    tags: ['arcade', 'ball', 'paddles', 'retro'],
    contexts: ['chat', 'terminal', 'button', 'card'],
    collections: ['arcade', 'agent'],
    addedAt: ADDED_AT,
    ...BUILTIN,
  },
  {
    id: 'alien-march',
    name: 'Alien March',
    description: 'A row of tiny aliens steps, drops and wiggles its legs while a cannon waits below.',
    intent: 'playful',
    cols: 9,
    rows: 8,
    states: {
      idle: { kind: 'recipe', recipe: 'arcade', params: { variant: 'march-idle' } },
      thinking: { kind: 'recipe', recipe: 'arcade', params: { variant: 'march' } },
      debugging: { kind: 'recipe', recipe: 'arcade', params: { variant: 'march-shoot' } },
      success: { kind: 'recipe', recipe: 'arcade', params: { variant: 'march-clear' } },
      error: { kind: 'recipe', recipe: 'arcade', params: { variant: 'march-invaded' } },
    },
    transition: 'cut',
    tags: ['arcade', 'aliens', 'bugs', 'retro'],
    contexts: ['page', 'splash', 'card', 'terminal'],
    collections: ['arcade'],
    addedAt: ADDED_AT,
    ...BUILTIN,
  },
  {
    id: 'chomper',
    name: 'Chomper',
    description:
      'A round mouth chomps along a row of pellets, eating each one, then wraps round like a maze tunnel.',
    intent: 'progress',
    cols: 11,
    rows: 5,
    states: {
      idle: { kind: 'recipe', recipe: 'arcade', params: { variant: 'chomp-rest' } },
      thinking: { kind: 'recipe', recipe: 'arcade', params: { variant: 'chomp' } },
      progress: { kind: 'recipe', recipe: 'arcade', params: { variant: 'chomp-progress' } },
      success: { kind: 'recipe', recipe: 'arcade', params: { variant: 'chomp-done' } },
      error: { kind: 'recipe', recipe: 'arcade', params: { variant: 'chomp-caught' } },
    },
    transition: 'cut',
    tags: ['arcade', 'tokens', 'eat', 'retro'],
    contexts: ['chat', 'inline', 'card', 'terminal'],
    collections: ['arcade'],
    addedAt: ADDED_AT,
    ...BUILTIN,
  },
  {
    id: 'snake-hunt',
    name: 'Hungry Snake',
    description: 'A snake steers across the grid to food, eats it and grows, and on success fills the board.',
    intent: 'thinking',
    cols: 8,
    rows: 8,
    states: {
      idle: { kind: 'recipe', recipe: 'arcade', params: { variant: 'hunt-coil' } },
      thinking: { kind: 'recipe', recipe: 'arcade', params: { variant: 'hunt' } },
      waiting: { kind: 'recipe', recipe: 'arcade', params: { variant: 'hunt-wait' } },
      success: { kind: 'recipe', recipe: 'arcade', params: { variant: 'hunt-fill' } },
      error: { kind: 'recipe', recipe: 'arcade', params: { variant: 'hunt-crash' } },
    },
    transition: 'cut',
    tags: ['snake', 'arcade', 'grow', 'retro'],
    contexts: ['card', 'page', 'terminal', 'splash'],
    collections: ['arcade'],
    addedAt: ADDED_AT,
    ...BUILTIN,
  },
  {
    id: 'brick-wall',
    name: 'Brick Wall',
    description:
      'A ball knocks bricks out of a wall one hit at a time, and the last brick falling is the done moment.',
    intent: 'progress',
    cols: 9,
    rows: 9,
    states: {
      idle: { kind: 'recipe', recipe: 'arcade', params: { variant: 'bricks-rest' } },
      thinking: { kind: 'recipe', recipe: 'arcade', params: { variant: 'bricks' } },
      progress: { kind: 'recipe', recipe: 'arcade', params: { variant: 'bricks-progress' } },
      success: { kind: 'recipe', recipe: 'arcade', params: { variant: 'bricks-clear' } },
      error: { kind: 'recipe', recipe: 'arcade', params: { variant: 'bricks-miss' } },
    },
    transition: 'cut',
    tags: ['arcade', 'bricks', 'progress', 'retro'],
    contexts: ['card', 'page', 'splash'],
    collections: ['arcade'],
    addedAt: ADDED_AT,
    ...BUILTIN,
  },
  {
    id: 'runner',
    name: 'Hurdle Runner',
    description:
      'A tiny figure runs on a scrolling ground line and hops over posts, the offline waiting game.',
    intent: 'loading',
    cols: 12,
    rows: 6,
    states: {
      idle: { kind: 'recipe', recipe: 'arcade', params: { variant: 'run-stand' } },
      thinking: { kind: 'recipe', recipe: 'arcade', params: { variant: 'run' } },
      offline: { kind: 'recipe', recipe: 'arcade', params: { variant: 'run-empty' } },
      success: { kind: 'recipe', recipe: 'arcade', params: { variant: 'run-finish' } },
      error: { kind: 'recipe', recipe: 'arcade', params: { variant: 'run-crash' } },
    },
    transition: 'cut',
    tags: ['runner', 'offline', 'arcade', 'retry'],
    contexts: ['page', 'card', 'splash', 'terminal'],
    collections: ['arcade', 'agent'],
    addedAt: ADDED_AT,
    ...BUILTIN,
  },
  {
    id: 'corner-hit',
    name: 'Corner Hit',
    description:
      'A block drifts and bounces off the walls, always just missing a corner, until success lands it exactly.',
    intent: 'result',
    cols: 10,
    rows: 8,
    states: {
      idle: { kind: 'recipe', recipe: 'arcade', params: { variant: 'corner-drift' } },
      thinking: { kind: 'recipe', recipe: 'arcade', params: { variant: 'corner', seed: CORNER_SEED } },
      waiting: { kind: 'recipe', recipe: 'arcade', params: { variant: 'corner-wait' } },
      success: { kind: 'recipe', recipe: 'arcade', params: { variant: 'corner-hit' } },
      error: { kind: 'recipe', recipe: 'arcade', params: { variant: 'corner-near' } },
    },
    transition: 'cut',
    tags: ['screensaver', 'bounce', 'meme', 'celebrate'],
    contexts: ['card', 'page', 'splash', 'button'],
    collections: ['arcade'],
    addedAt: ADDED_AT,
    ...BUILTIN,
  },
  {
    id: 'reels',
    name: 'Reels',
    description:
      'Three reels spin, then stop left to right with a small overshoot, and light the payline if they match.',
    intent: 'result',
    cols: 11,
    rows: 5,
    states: {
      idle: { kind: 'recipe', recipe: 'arcade', params: { variant: 'reels-rest' } },
      thinking: { kind: 'recipe', recipe: 'arcade', params: { variant: 'reels' } },
      generating: { kind: 'recipe', recipe: 'arcade', params: { variant: 'reels-stagger' } },
      success: { kind: 'recipe', recipe: 'arcade', params: { variant: 'reels-win' } },
      error: { kind: 'recipe', recipe: 'arcade', params: { variant: 'reels-lose' } },
    },
    transition: 'cut',
    tags: ['slots', 'generate', 'pick', 'arcade'],
    contexts: ['card', 'button', 'page', 'chat'],
    collections: ['arcade'],
    addedAt: ADDED_AT,
    ...BUILTIN,
  },
  {
    id: 'dice',
    name: 'Dice',
    description: 'A die tumbles across the grid, its faces blurring, then lands on a face and stays.',
    intent: 'result',
    cols: 7,
    rows: 7,
    states: {
      idle: { kind: 'recipe', recipe: 'arcade', params: { variant: 'dice-rest' } },
      thinking: { kind: 'recipe', recipe: 'arcade', params: { variant: 'dice' } },
      sampling: { kind: 'recipe', recipe: 'arcade', params: { variant: 'dice-sample' } },
      success: { kind: 'recipe', recipe: 'arcade', params: { variant: 'dice', glyph: 'six' } },
      error: { kind: 'recipe', recipe: 'arcade', params: { variant: 'dice', glyph: 'one' } },
    },
    transition: 'flip',
    tags: ['dice', 'random', 'sample', 'compact'],
    contexts: ['inline', 'button', 'chat', 'card'],
    collections: ['arcade'],
    addedAt: ADDED_AT,
    ...BUILTIN,
  },
] as const satisfies readonly IndicatorSet[];
