import type { IndicatorSet } from '../../core/types';
import { BUILTIN } from '../shared';

const ADDED_AT = '2026-09-29';
const COLLECTION = 'emergence';

/** The eight Emergence sets: automata, mazes, sorting, crystals and fireflies. */
export const EMERGENCE_SETS = [
  {
    id: 'maze-solve',
    name: 'Maze Solve',
    description:
      'A maze carves itself dot by dot, then every dead end retracts until only the path from corner to corner is left.',
    intent: 'thinking',
    cols: 9,
    rows: 9,
    states: {
      idle: { kind: 'recipe', recipe: 'grow', params: { variant: 'maze-path' } },
      thinking: { kind: 'recipe', recipe: 'grow', params: { variant: 'maze' } },
      waiting: { kind: 'recipe', recipe: 'grow', params: { variant: 'maze-wait' } },
      success: { kind: 'recipe', recipe: 'grow', params: { variant: 'maze-trace' } },
      error: { kind: 'recipe', recipe: 'grow', params: { variant: 'maze-collapse' } },
    },
    transition: 'cut',
    tags: ['maze', 'reasoning', 'search', 'algorithm'],
    contexts: ['card', 'page', 'splash', 'chat'],
    collections: [COLLECTION],
    addedAt: ADDED_AT,
    ...BUILTIN,
  },
  {
    id: 'sort-pass',
    name: 'Sort Pass',
    description:
      'Shuffled bars swap neighbour by neighbour into a clean staircase, then a check sweep runs across them.',
    intent: 'progress',
    cols: 8,
    rows: 8,
    states: {
      idle: { kind: 'recipe', recipe: 'columns', params: { variant: 'sort-done' } },
      thinking: { kind: 'recipe', recipe: 'columns', params: { variant: 'sort' } },
      ranking: { kind: 'recipe', recipe: 'columns', params: { variant: 'sort-insert' } },
      success: { kind: 'recipe', recipe: 'columns', params: { variant: 'sort-verify' } },
      error: { kind: 'recipe', recipe: 'columns', params: { variant: 'sort-bogo' } },
    },
    transition: 'cut',
    tags: ['sorting', 'ranking', 'algorithm', 'bars'],
    contexts: ['card', 'button', 'inline', 'terminal', 'chat'],
    collections: [COLLECTION, 'term'],
    addedAt: ADDED_AT,
    ...BUILTIN,
  },
  {
    id: 'rule-stream',
    name: 'Rule Stream',
    description:
      'A one-dimensional automaton grows a perfect Sierpinski triangle from one dot that meets itself and vanishes.',
    intent: 'thinking',
    cols: 16,
    rows: 9,
    states: {
      idle: { kind: 'recipe', recipe: 'automaton', params: { variant: 'rule-90', frames: 1 } },
      thinking: { kind: 'recipe', recipe: 'automaton', params: { variant: 'rule-90' } },
      working: { kind: 'recipe', recipe: 'automaton', params: { variant: 'rule-30' } },
      success: { kind: 'recipe', recipe: 'automaton', params: { variant: 'rule-90', glyph: 'check' } },
      error: { kind: 'recipe', recipe: 'automaton', params: { variant: 'rule-204' } },
    },
    transition: 'cut',
    tags: ['automaton', 'fractal', 'math', 'terminal'],
    contexts: ['splash', 'page', 'card', 'terminal'],
    collections: [COLLECTION],
    addedAt: ADDED_AT,
    ...BUILTIN,
  },
  {
    id: 'flood-search',
    name: 'Flood Search',
    description:
      'A search wavefront spreads from a start dot, bends around walls like water, then traces the shortest path back.',
    intent: 'thinking',
    cols: 9,
    rows: 9,
    states: {
      idle: { kind: 'recipe', recipe: 'grow', params: { variant: 'flood-rest' } },
      thinking: { kind: 'recipe', recipe: 'grow', params: { variant: 'flood' } },
      waiting: { kind: 'recipe', recipe: 'grow', params: { variant: 'flood-wait' } },
      success: { kind: 'recipe', recipe: 'grow', params: { variant: 'flood-path' } },
      error: { kind: 'recipe', recipe: 'grow', params: { variant: 'flood-sealed' } },
    },
    transition: 'cut',
    tags: ['pathfinding', 'search', 'agent', 'algorithm'],
    contexts: ['card', 'page', 'splash', 'chat'],
    collections: [COLLECTION, 'agent'],
    addedAt: ADDED_AT,
    ...BUILTIN,
  },
  {
    id: 'ant-rewind',
    name: 'Ant Rewind',
    description:
      'A single ant scribbles an ever more complex pattern, then time runs backward and it un-draws everything exactly.',
    intent: 'thinking',
    cols: 11,
    rows: 11,
    states: {
      idle: { kind: 'recipe', recipe: 'automaton', params: { variant: 'ant-rest' } },
      thinking: { kind: 'recipe', recipe: 'automaton', params: { variant: 'ant' } },
      undo: { kind: 'recipe', recipe: 'automaton', params: { variant: 'ant-undo' } },
      success: { kind: 'recipe', recipe: 'automaton', params: { variant: 'ant-home' } },
      error: { kind: 'recipe', recipe: 'automaton', params: { variant: 'ant-freeze' } },
    },
    transition: 'cut',
    tags: ['automaton', 'reversible', 'undo', 'math'],
    contexts: ['splash', 'page', 'card'],
    collections: [COLLECTION],
    addedAt: ADDED_AT,
    ...BUILTIN,
  },
  {
    id: 'turing-spots',
    name: 'Turing Spots',
    description:
      'Reaction-diffusion spots swell, split in two like dividing cells and push apart until they tile the grid.',
    intent: 'loading',
    cols: 16,
    rows: 16,
    states: {
      idle: { kind: 'recipe', recipe: 'automaton', params: { variant: 'spots-breathe' } },
      thinking: { kind: 'recipe', recipe: 'automaton', params: { variant: 'spots' } },
      growing: { kind: 'recipe', recipe: 'automaton', params: { variant: 'spots-coral' } },
      success: { kind: 'recipe', recipe: 'automaton', params: { variant: 'spots-pulse' } },
      error: { kind: 'recipe', recipe: 'automaton', params: { variant: 'spots-labyrinth' } },
    },
    transition: 'crossfade',
    tags: ['biology', 'reaction-diffusion', 'growth', 'organic'],
    contexts: ['splash', 'page'],
    collections: [COLLECTION],
    addedAt: ADDED_AT,
    ...BUILTIN,
  },
  {
    id: 'frost',
    name: 'Frost',
    description:
      'A wandering particle sticks to a growing crystal, and a branching frost pattern grows out from the centre.',
    intent: 'loading',
    cols: 11,
    rows: 11,
    states: {
      idle: { kind: 'recipe', recipe: 'grow', params: { variant: 'dla-rest' } },
      thinking: { kind: 'recipe', recipe: 'grow', params: { variant: 'dla' } },
      progress: { kind: 'recipe', recipe: 'grow', params: { variant: 'dla-progress' } },
      success: { kind: 'recipe', recipe: 'grow', params: { variant: 'dla-tips' } },
      error: { kind: 'recipe', recipe: 'grow', params: { variant: 'dla-shatter' } },
    },
    transition: 'cut',
    tags: ['crystal', 'growth', 'frost', 'branching'],
    contexts: ['splash', 'page', 'card'],
    collections: [COLLECTION],
    addedAt: ADDED_AT,
    ...BUILTIN,
  },
  {
    id: 'fireflies',
    name: 'Fireflies',
    description:
      "Scattered fireflies blink out of step, nudge each other's clocks and slowly lock into one shared flash.",
    intent: 'thinking',
    cols: 10,
    rows: 10,
    states: {
      idle: { kind: 'recipe', recipe: 'particles', params: { variant: 'fireflies', density: 0 } },
      thinking: { kind: 'recipe', recipe: 'particles', params: { variant: 'fireflies' } },
      waiting: { kind: 'recipe', recipe: 'particles', params: { variant: 'fireflies-beat' } },
      success: { kind: 'recipe', recipe: 'particles', params: { variant: 'fireflies-sync' } },
      error: { kind: 'recipe', recipe: 'particles', params: { variant: 'fireflies-scatter' } },
    },
    transition: 'crossfade',
    tags: ['emergence', 'sync', 'swarm', 'agents'],
    contexts: ['splash', 'page', 'card', 'chat'],
    collections: [COLLECTION],
    addedAt: ADDED_AT,
    ...BUILTIN,
  },
] as const satisfies readonly IndicatorSet[];
