import {
  ATTENTION_STATES,
  type CatalogSet,
  FILL_BAR_IDLE,
  HEART_IDLE,
  NEW_SET_DATE,
  RING_FILL_THINKING,
  SEND_IDLE,
  SPARKLE_STATES,
  STEPS_IDLE,
  TOOL_CALL_STATES,
  toFullStates,
  toRecipe,
} from './catalog-frames';
import { LOADING_SETS, THINKING_SETS } from './catalog-thinking-loading';

export type { CatalogSet } from './catalog-frames';

const PROGRESS_SETS: readonly CatalogSet[] = [
  {
    id: 'fill-bar',
    name: 'Progress Bar',
    description: 'A thin track that fills column by column, flashes when full, then starts again.',
    intent: 'progress',
    cols: 12,
    rows: 3,
    states: { ...toFullStates(toRecipe('fill')), idle: FILL_BAR_IDLE },
    transition: 'cut',
    tags: ['progress', 'bar', 'determinate', 'terminal'],
    contexts: ['terminal', 'card', 'page', 'button'],
    collections: ['term'],
    addedAt: NEW_SET_DATE,
  },
  {
    id: 'type',
    name: 'Typewriter',
    description: 'Dot-words stream out behind a steady caret, like a reply being written.',
    intent: 'progress',
    cols: 10,
    rows: 3,
    states: toFullStates(toRecipe('typewriter')),
    transition: 'cut',
    tags: ['progress', 'text', 'terminal'],
    contexts: ['terminal', 'inline', 'chat'],
    collections: ['term'],
    addedAt: '2026-09-22',
  },
  {
    id: 'steps',
    name: 'Steps',
    description: 'A row of step dots: finished steps stand tall, the current one blinks.',
    intent: 'progress',
    cols: 9,
    rows: 3,
    states: { ...toFullStates(toRecipe('fill', { length: 5 })), idle: STEPS_IDLE },
    transition: 'cut',
    tags: ['steps', 'progress', 'agent', 'multi-step'],
    contexts: ['terminal', 'chat', 'inline', 'card'],
    collections: ['minimal', 'agent'],
    addedAt: NEW_SET_DATE,
  },
  {
    id: 'ring-fill',
    name: 'Ring Fill',
    description: 'Dots light clockwise around a small ring until it closes, then a centre dot marks done.',
    intent: 'progress',
    cols: 5,
    rows: 5,
    states: toFullStates(RING_FILL_THINKING),
    transition: 'flip',
    tags: ['progress', 'ring', 'determinate', 'compact'],
    contexts: ['button', 'inline', 'chat', 'card'],
    collections: [],
    addedAt: NEW_SET_DATE,
  },
];

const RESULT_SETS: readonly CatalogSet[] = [
  {
    id: 'okfail',
    name: 'Done / Failed',
    description: 'A check or a cross drawn stroke by stroke to show how a task ended.',
    intent: 'result',
    cols: 7,
    rows: 7,
    states: { idle: toRecipe('idle'), success: toRecipe('check'), error: toRecipe('cross') },
    transition: 'flip',
    tags: ['result', 'icons'],
    contexts: ['button', 'inline', 'chat'],
    collections: [],
    addedAt: '2026-08-21',
  },
  {
    id: 'tool-call',
    name: 'Tool Call',
    description:
      'A tiny bullet that blinks while a tool runs, then shows done, failed, waiting or cancelled.',
    intent: 'result',
    cols: 3,
    rows: 3,
    states: TOOL_CALL_STATES,
    transition: 'cut',
    tags: ['agent', 'tool', 'terminal', 'status'],
    contexts: ['terminal', 'chat', 'inline'],
    collections: ['agent', 'term'],
    addedAt: NEW_SET_DATE,
  },
  {
    id: 'attention',
    name: 'Attention',
    description:
      'A calm set for when an agent needs you: pause bars while waiting, a blinking mark for warnings.',
    intent: 'result',
    cols: 5,
    rows: 5,
    states: ATTENTION_STATES,
    transition: 'cut',
    tags: ['agent', 'waiting', 'warning', 'status'],
    contexts: ['terminal', 'chat', 'card', 'inline'],
    collections: ['agent'],
    addedAt: NEW_SET_DATE,
  },
];

const PLAYFUL_SETS: readonly CatalogSet[] = [
  {
    id: 'bounce',
    name: 'Bounce',
    description: 'A ball that bounces across the grid with a dot trailing behind it.',
    intent: 'playful',
    cols: 8,
    rows: 6,
    states: toFullStates(toRecipe('bounce', { trail: 1 })),
    transition: 'flip',
    tags: ['ball', 'fun'],
    contexts: ['button', 'card', 'splash'],
    collections: [],
    addedAt: '2026-09-26',
  },
  {
    id: 'life',
    name: 'Life',
    description: "Conway's Game of Life playing out on a 12×12 grid.",
    intent: 'playful',
    cols: 12,
    rows: 12,
    states: { thinking: toRecipe('life', { density: 0, frames: 48 }) },
    transition: 'cut',
    tags: ['generative', 'conway'],
    contexts: ['page', 'splash'],
    collections: [],
    addedAt: '2026-09-14',
  },
  {
    id: 'rain',
    name: 'Rain',
    description: 'Drops that fall down every column at different speeds.',
    intent: 'playful',
    cols: 8,
    rows: 8,
    states: { idle: toRecipe('idle'), thinking: toRecipe('rain') },
    transition: 'crossfade',
    tags: ['weather', 'ambient'],
    contexts: ['page', 'splash', 'card'],
    collections: [],
    addedAt: '2026-09-25',
  },
];

const ICON_SETS: readonly CatalogSet[] = [
  {
    id: 'sparkle',
    name: 'Sparkle',
    description:
      'A four-point star that swells and twinkles with a small glint in the corner, the AI mark in dots.',
    intent: 'icons',
    cols: 7,
    rows: 7,
    states: SPARKLE_STATES,
    transition: 'crossfade',
    tags: ['ai', 'sparkle', 'icon', 'star'],
    contexts: ['button', 'inline', 'chat', 'card'],
    collections: ['ai'],
    addedAt: NEW_SET_DATE,
  },
  {
    id: 'heart',
    name: 'Heartbeat',
    description: 'A heart that beats twice and rests, for likes and favourites.',
    intent: 'icons',
    cols: 7,
    rows: 6,
    states: { idle: HEART_IDLE, thinking: toRecipe('heart'), success: toRecipe('check') },
    transition: 'crossfade',
    tags: ['icon', 'like'],
    contexts: ['button', 'inline', 'chat'],
    collections: [],
    addedAt: '2026-09-06',
  },
  {
    id: 'send',
    name: 'Sending',
    description: 'An arrow that slides to the right while a message sends.',
    intent: 'icons',
    cols: 7,
    rows: 7,
    states: {
      idle: SEND_IDLE,
      thinking: toRecipe('arrow'),
      success: toRecipe('check'),
      error: toRecipe('cross'),
    },
    transition: 'flip',
    tags: ['icon', 'send', 'chat'],
    contexts: ['button', 'chat', 'inline'],
    collections: [],
    addedAt: '2026-09-12',
  },
];

export const CATALOG_SETS: readonly CatalogSet[] = [
  ...THINKING_SETS,
  ...LOADING_SETS,
  ...PROGRESS_SETS,
  ...RESULT_SETS,
  ...PLAYFUL_SETS,
  ...ICON_SETS,
];
