import {
  type CatalogSet,
  EQUALIZER_STATES,
  NEW_SET_DATE,
  SHIMMER_IDLE,
  SKELETON_IDLE,
  toFullStates,
  toRecipe,
} from './catalog-frames';

export const THINKING_SETS: readonly CatalogSet[] = [
  {
    id: 'pulse',
    name: 'Thinking Pulse',
    description: 'A centre dot that blooms into an eight-point star and settles back, made for AI replies.',
    intent: 'thinking',
    cols: 7,
    rows: 7,
    states: toFullStates(toRecipe('pulse')),
    transition: 'flip',
    tags: ['pulse', 'asterisk', 'chat'],
    contexts: ['chat', 'terminal', 'button', 'card'],
    collections: ['ai'],
    addedAt: '2026-08-19',
  },
  {
    id: 'typing-hop',
    name: 'Typing Hop',
    description: 'Three dots that hop up one after another, like someone typing a reply.',
    intent: 'thinking',
    cols: 7,
    rows: 3,
    states: toFullStates(toRecipe('hop')),
    transition: 'cut',
    tags: ['typing', 'chat', 'minimal', 'dots'],
    contexts: ['chat', 'inline', 'button'],
    collections: ['minimal', 'ai'],
    addedAt: NEW_SET_DATE,
  },
  {
    id: 'shimmer',
    name: 'Shimmer',
    description: 'A bright slanted band sweeps across a dim strip, then rests, like a live status label.',
    intent: 'thinking',
    cols: 12,
    rows: 3,
    states: { ...toFullStates(toRecipe('shimmer', { trail: 4 })), idle: SHIMMER_IDLE },
    transition: 'crossfade',
    tags: ['shimmer', 'ai', 'label', 'wide'],
    contexts: ['inline', 'chat', 'button', 'terminal'],
    collections: ['ai'],
    addedAt: NEW_SET_DATE,
  },
  {
    id: 'dots3',
    name: 'Three Dot',
    description: 'The classic three-dot ellipsis, filling in one dot at a time.',
    intent: 'thinking',
    cols: 9,
    rows: 3,
    states: toFullStates(toRecipe('ellipsis')),
    transition: 'cut',
    tags: ['minimal', 'ellipsis', 'chat'],
    contexts: ['chat', 'inline', 'button'],
    collections: ['minimal'],
    addedAt: '2026-07-30',
  },
  {
    id: 'ember',
    name: 'Ember Pulse',
    description: 'A compact star that grows from one dot and settles back, sized for inline text.',
    intent: 'thinking',
    cols: 5,
    rows: 5,
    states: toFullStates(toRecipe('pulse')),
    transition: 'crossfade',
    tags: ['pulse', 'star', 'compact'],
    contexts: ['chat', 'inline', 'terminal'],
    collections: ['ai', 'term'],
    addedAt: '2026-09-19',
  },
  {
    id: 'radar',
    name: 'Radar',
    description: 'A beam that sweeps around a centre dot, like a radar searching.',
    intent: 'thinking',
    cols: 9,
    rows: 9,
    states: toFullStates(toRecipe('radar')),
    transition: 'flip',
    tags: ['sweep', 'search'],
    contexts: ['page', 'card', 'splash'],
    collections: [],
    addedAt: '2026-08-29',
  },
  {
    id: 'breathe',
    name: 'Breathe',
    description: 'A square that slowly grows and shrinks, calm enough for a terminal.',
    intent: 'thinking',
    cols: 5,
    rows: 5,
    states: toFullStates(toRecipe('breathe')),
    transition: 'crossfade',
    tags: ['calm', 'terminal', 'compact'],
    contexts: ['terminal', 'inline', 'button'],
    collections: ['term'],
    addedAt: '2026-08-09',
  },
];

export const LOADING_SETS: readonly CatalogSet[] = [
  {
    id: 'braille',
    name: 'Braille Spinner',
    description: 'Three dots chase around a tiny ring, the classic terminal spinner redrawn in dots.',
    intent: 'loading',
    cols: 3,
    rows: 3,
    states: toFullStates(toRecipe('snake')),
    transition: 'cut',
    tags: ['spinner', 'terminal', 'compact', 'braille'],
    contexts: ['terminal', 'inline', 'button', 'chat'],
    collections: ['term', 'minimal'],
    addedAt: NEW_SET_DATE,
  },
  {
    id: 'arc',
    name: 'Arc Spinner',
    description: 'A long arc that turns around a round ring, the everyday loading spinner in dots.',
    intent: 'loading',
    cols: 9,
    rows: 9,
    states: toFullStates(toRecipe('orbit', { trail: 6 })),
    transition: 'flip',
    tags: ['spinner', 'ring', 'loop'],
    contexts: ['button', 'card', 'page', 'chat'],
    collections: [],
    addedAt: NEW_SET_DATE,
  },
  {
    id: 'orbit',
    name: 'Orbit',
    description: 'A dot with a short tail that circles a round ring.',
    intent: 'loading',
    cols: 7,
    rows: 7,
    states: toFullStates(toRecipe('orbit')),
    transition: 'flip',
    tags: ['spinner', 'loop'],
    contexts: ['button', 'page', 'card'],
    collections: [],
    addedAt: '2026-08-14',
  },
  {
    id: 'scanner',
    name: 'Scanner',
    description: 'A bright bar with a short tail glides left and right, pausing at each end.',
    intent: 'loading',
    cols: 10,
    rows: 3,
    states: toFullStates(toRecipe('scanner')),
    transition: 'flip',
    tags: ['scanner', 'bar', 'terminal', 'indeterminate'],
    contexts: ['terminal', 'button', 'inline', 'page'],
    collections: ['term'],
    addedAt: NEW_SET_DATE,
  },
  {
    id: 'equalizer',
    name: 'Equalizer',
    description:
      'Bars that rise and fall like a level meter, with listening and connecting states for voice.',
    intent: 'loading',
    cols: 9,
    rows: 7,
    states: {
      idle: EQUALIZER_STATES.idle,
      thinking: toRecipe('bars'),
      listening: EQUALIZER_STATES.listening,
      connecting: EQUALIZER_STATES.connecting,
      success: toRecipe('check'),
      error: toRecipe('cross'),
    },
    transition: 'crossfade',
    tags: ['voice', 'audio', 'bars', 'agent'],
    contexts: ['chat', 'card', 'button', 'page'],
    collections: ['agent'],
    addedAt: NEW_SET_DATE,
  },
  {
    id: 'skeleton',
    name: 'Skeleton Lines',
    description: 'Three ragged lines of dots with a shimmer passing over them while content loads.',
    intent: 'loading',
    cols: 16,
    rows: 7,
    states: { ...toFullStates(toRecipe('shimmer', { trail: 4 })), idle: SKELETON_IDLE },
    transition: 'crossfade',
    tags: ['skeleton', 'placeholder', 'wide', 'content'],
    contexts: ['card', 'page', 'chat'],
    collections: [],
    addedAt: NEW_SET_DATE,
  },
  {
    id: 'grid-wave',
    name: 'Grid Wave',
    description: 'A three by three grid of blocks that blinks out and back in a diagonal wave.',
    intent: 'loading',
    cols: 8,
    rows: 8,
    states: toFullStates(toRecipe('cascade')),
    transition: 'crossfade',
    tags: ['grid', 'cube', 'wave'],
    contexts: ['card', 'page', 'chat', 'button'],
    collections: [],
    addedAt: NEW_SET_DATE,
  },
  {
    id: 'snake',
    name: 'Snake',
    description: 'A short snake that runs around the border of a 5×5 grid.',
    intent: 'loading',
    cols: 5,
    rows: 5,
    states: toFullStates(toRecipe('snake')),
    transition: 'flip',
    tags: ['terminal', 'spinner', 'compact'],
    contexts: ['terminal', 'button', 'inline'],
    collections: ['term'],
    addedAt: '2026-08-24',
  },
  {
    id: 'ripple',
    name: 'Ripple',
    description: 'Rings that spread out from the centre one at a time, then a short pause.',
    intent: 'loading',
    cols: 9,
    rows: 9,
    states: toFullStates(toRecipe('ripple')),
    transition: 'crossfade',
    tags: ['ring', 'splash'],
    contexts: ['page', 'splash', 'card'],
    collections: [],
    addedAt: '2026-08-31',
  },
];
