import type { IndicatorSet, RecipeId, StateName } from '../core/types';

export type PresetGroup =
  | 'thinking'
  | 'loading'
  | 'progress'
  | 'result'
  | 'playful'
  | 'icons'
  | 'ai-life'
  | 'arcade'
  | 'demoscene'
  | 'emergence'
  | 'nature'
  | 'signboard'
  | 'solid';

export interface PresetEntry {
  readonly group: PresetGroup;
  readonly cols: number;
  readonly rows: number;
  readonly state: StateName;
  readonly poster: readonly number[];
  readonly recipes: readonly RecipeId[];
}

export const PRESET_GROUPS: Readonly<Record<PresetGroup, () => Promise<readonly IndicatorSet[]>>> = {
  thinking: () => import('./thinking').then((m) => m.THINKING_PRESETS),
  loading: () => import('./loading').then((m) => m.LOADING_PRESETS),
  progress: () => import('./progress').then((m) => m.PROGRESS_PRESETS),
  result: () => import('./result').then((m) => m.RESULT_PRESETS),
  playful: () => import('./playful').then((m) => m.PLAYFUL_PRESETS),
  icons: () => import('./icons').then((m) => m.ICON_PRESETS),
  'ai-life': () => import('./wow/ai-life').then((m) => m.AILIFE_SETS),
  arcade: () => import('./wow/arcade').then((m) => m.ARCADE_SETS),
  demoscene: () => import('./wow/demoscene').then((m) => m.DEMOSCENE_SETS),
  emergence: () => import('./wow/emergence').then((m) => m.EMERGENCE_SETS),
  nature: () => import('./wow/nature').then((m) => m.NATURE_SETS),
  signboard: () => import('./wow/signboard').then((m) => m.SIGNBOARD_SETS),
  solid: () => import('./wow/solid').then((m) => m.SOLID_SETS),
};

export const PRESET_MANIFEST: Readonly<Record<string, PresetEntry>> = {
  pulse: {
    group: 'thinking',
    cols: 7,
    rows: 7,
    state: 'thinking',
    poster: [0, 0, 0, 8, 0, 0, 0],
    recipes: ['check', 'cross', 'idle', 'pulse'],
  },
  'typing-hop': {
    group: 'thinking',
    cols: 7,
    rows: 3,
    state: 'thinking',
    poster: [0, 42, 0],
    recipes: ['check', 'cross', 'hop', 'idle'],
  },
  shimmer: {
    group: 'thinking',
    cols: 12,
    rows: 3,
    state: 'thinking',
    poster: [3754, 3413, 2730],
    recipes: ['check', 'cross', 'shimmer'],
  },
  dots3: {
    group: 'thinking',
    cols: 9,
    rows: 3,
    state: 'thinking',
    poster: [0, 0, 0],
    recipes: ['check', 'cross', 'ellipsis', 'idle'],
  },
  ember: {
    group: 'thinking',
    cols: 5,
    rows: 5,
    state: 'thinking',
    poster: [0, 0, 4, 0, 0],
    recipes: ['check', 'cross', 'idle', 'pulse'],
  },
  radar: {
    group: 'thinking',
    cols: 9,
    rows: 9,
    state: 'thinking',
    poster: [112, 240, 112, 48, 16, 0, 0, 0, 0],
    recipes: ['check', 'cross', 'idle', 'radar'],
  },
  breathe: {
    group: 'thinking',
    cols: 5,
    rows: 5,
    state: 'thinking',
    poster: [0, 0, 4, 0, 0],
    recipes: ['breathe', 'check', 'cross', 'idle'],
  },
  braille: {
    group: 'loading',
    cols: 3,
    rows: 3,
    state: 'thinking',
    poster: [4, 4, 4],
    recipes: ['check', 'cross', 'idle', 'snake'],
  },
  arc: {
    group: 'loading',
    cols: 9,
    rows: 9,
    state: 'thinking',
    poster: [48, 64, 128, 256, 256, 256, 0, 0, 0],
    recipes: ['check', 'cross', 'idle', 'orbit'],
  },
  orbit: {
    group: 'loading',
    cols: 7,
    rows: 7,
    state: 'thinking',
    poster: [24, 32, 0, 0, 0, 0, 0],
    recipes: ['check', 'cross', 'idle', 'orbit'],
  },
  scanner: {
    group: 'loading',
    cols: 10,
    rows: 3,
    state: 'thinking',
    poster: [512, 512, 512],
    recipes: ['check', 'cross', 'idle', 'scanner'],
  },
  equalizer: {
    group: 'loading',
    cols: 9,
    rows: 7,
    state: 'thinking',
    poster: [0, 320, 336, 341, 336, 320, 0],
    recipes: ['bars', 'check', 'cross'],
  },
  skeleton: {
    group: 'loading',
    cols: 16,
    rows: 7,
    state: 'thinking',
    poster: [0, 30037, 0, 21840, 0, 21760, 0],
    recipes: ['check', 'cross', 'shimmer'],
  },
  'grid-wave': {
    group: 'loading',
    cols: 8,
    rows: 8,
    state: 'thinking',
    poster: [27, 27, 0, 219, 219, 0, 219, 219],
    recipes: ['cascade', 'check', 'cross', 'idle'],
  },
  snake: {
    group: 'loading',
    cols: 5,
    rows: 5,
    state: 'thinking',
    poster: [16, 16, 16, 16, 0],
    recipes: ['check', 'cross', 'idle', 'snake'],
  },
  ripple: {
    group: 'loading',
    cols: 9,
    rows: 9,
    state: 'thinking',
    poster: [0, 0, 0, 0, 16, 0, 0, 0, 0],
    recipes: ['check', 'cross', 'idle', 'ripple'],
  },
  'fill-bar': {
    group: 'progress',
    cols: 12,
    rows: 3,
    state: 'thinking',
    poster: [2048, 4095, 2048],
    recipes: ['check', 'cross', 'fill'],
  },
  type: {
    group: 'progress',
    cols: 10,
    rows: 3,
    state: 'thinking',
    poster: [512, 512, 512],
    recipes: ['check', 'cross', 'idle', 'typewriter'],
  },
  steps: {
    group: 'progress',
    cols: 9,
    rows: 3,
    state: 'thinking',
    poster: [256, 341, 256],
    recipes: ['check', 'cross', 'fill'],
  },
  'ring-fill': {
    group: 'progress',
    cols: 5,
    rows: 5,
    state: 'thinking',
    poster: [4, 0, 0, 0, 0],
    recipes: ['check', 'cross', 'idle'],
  },
  okfail: {
    group: 'result',
    cols: 7,
    rows: 7,
    state: 'idle',
    poster: [0, 0, 0, 8, 0, 0, 0],
    recipes: ['check', 'cross', 'idle'],
  },
  'tool-call': {
    group: 'result',
    cols: 3,
    rows: 3,
    state: 'thinking',
    poster: [2, 7, 2],
    recipes: ['check', 'cross'],
  },
  attention: {
    group: 'result',
    cols: 5,
    rows: 5,
    state: 'idle',
    poster: [0, 0, 4, 0, 0],
    recipes: ['check', 'cross', 'idle'],
  },
  bounce: {
    group: 'playful',
    cols: 8,
    rows: 6,
    state: 'thinking',
    poster: [0, 0, 0, 0, 64, 128],
    recipes: ['bounce', 'check', 'cross', 'idle'],
  },
  life: {
    group: 'playful',
    cols: 12,
    rows: 12,
    state: 'thinking',
    poster: [1024, 512, 3584, 0, 160, 96, 64, 0, 2, 10, 6, 0],
    recipes: ['life'],
  },
  rain: {
    group: 'playful',
    cols: 8,
    rows: 8,
    state: 'thinking',
    poster: [16, 8, 72, 64, 2, 34, 37, 5],
    recipes: ['idle', 'rain'],
  },
  sparkle: {
    group: 'icons',
    cols: 7,
    rows: 7,
    state: 'thinking',
    poster: [1, 0, 0, 8, 0, 0, 0],
    recipes: ['check'],
  },
  heart: {
    group: 'icons',
    cols: 7,
    rows: 6,
    state: 'thinking',
    poster: [54, 127, 127, 62, 28, 8],
    recipes: ['check', 'heart'],
  },
  send: {
    group: 'icons',
    cols: 7,
    rows: 7,
    state: 'thinking',
    poster: [0, 0, 0, 64, 0, 0, 0],
    recipes: ['arrow', 'check', 'cross'],
  },
  eyes: {
    group: 'ai-life',
    cols: 12,
    rows: 8,
    state: 'thinking',
    poster: [0, 780, 1950, 1950, 1950, 1950, 780, 0],
    recipes: ['face'],
  },
  synapse: {
    group: 'ai-life',
    cols: 11,
    rows: 9,
    state: 'thinking',
    poster: [0, 576, 16, 64, 514, 64, 528, 1856, 512],
    recipes: ['network'],
  },
  'beam-search': {
    group: 'ai-life',
    cols: 12,
    rows: 12,
    state: 'thinking',
    poster: [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 32],
    recipes: ['grow'],
  },
  constellation: {
    group: 'ai-life',
    cols: 12,
    rows: 12,
    state: 'thinking',
    poster: [0, 0, 0, 0, 0, 0, 0, 0, 0, 4, 0, 0],
    recipes: ['network'],
  },
  critter: {
    group: 'ai-life',
    cols: 12,
    rows: 12,
    state: 'thinking',
    poster: [0, 14, 2, 6, 0, 4, 0, 496, 360, 360, 504, 504],
    recipes: [],
  },
  morph: {
    group: 'ai-life',
    cols: 9,
    rows: 9,
    state: 'thinking',
    poster: [0, 0, 0, 0, 0, 84, 0, 0, 0],
    recipes: ['hop', 'idle', 'resolve'],
  },
  circuit: {
    group: 'ai-life',
    cols: 12,
    rows: 7,
    state: 'thinking',
    poster: [0, 2048, 0, 7, 5, 7, 0],
    recipes: ['network'],
  },
  'stack-clear': {
    group: 'arcade',
    cols: 6,
    rows: 8,
    state: 'thinking',
    poster: [16, 28, 0, 0, 0, 0, 0, 0],
    recipes: ['arcade'],
  },
  rally: {
    group: 'arcade',
    cols: 9,
    rows: 5,
    state: 'thinking',
    poster: [384, 257, 257, 1, 0],
    recipes: ['arcade'],
  },
  'alien-march': {
    group: 'arcade',
    cols: 9,
    rows: 8,
    state: 'thinking',
    poster: [476, 340, 0, 0, 0, 0, 8, 28],
    recipes: ['arcade'],
  },
  chomper: {
    group: 'arcade',
    cols: 11,
    rows: 5,
    state: 'thinking',
    poster: [896, 1536, 1045, 1536, 896],
    recipes: ['arcade'],
  },
  'snake-hunt': {
    group: 'arcade',
    cols: 8,
    rows: 8,
    state: 'thinking',
    poster: [130, 128, 128, 0, 0, 0, 0, 0],
    recipes: ['arcade'],
  },
  'brick-wall': {
    group: 'arcade',
    cols: 9,
    rows: 9,
    state: 'thinking',
    poster: [511, 511, 0, 0, 0, 0, 0, 16, 56],
    recipes: ['arcade'],
  },
  runner: {
    group: 'arcade',
    cols: 12,
    rows: 6,
    state: 'thinking',
    poster: [0, 0, 512, 1537, 1025, 2031],
    recipes: ['arcade'],
  },
  'corner-hit': {
    group: 'arcade',
    cols: 10,
    rows: 8,
    state: 'thinking',
    poster: [384, 384, 0, 0, 0, 0, 0, 0],
    recipes: ['arcade'],
  },
  reels: {
    group: 'arcade',
    cols: 11,
    rows: 5,
    state: 'thinking',
    poster: [0, 32, 631, 1312, 512],
    recipes: ['arcade'],
  },
  dice: {
    group: 'arcade',
    cols: 7,
    rows: 7,
    state: 'thinking',
    poster: [0, 34, 0, 34, 0, 34, 0],
    recipes: ['arcade'],
  },
  'lava-lamp': {
    group: 'demoscene',
    cols: 12,
    rows: 8,
    state: 'thinking',
    poster: [0, 112, 248, 504, 504, 248, 112, 0],
    recipes: ['shader'],
  },
  corridor: {
    group: 'demoscene',
    cols: 9,
    rows: 9,
    state: 'thinking',
    poster: [0, 254, 130, 130, 138, 130, 130, 254, 0],
    recipes: ['shader'],
  },
  hyperspace: {
    group: 'demoscene',
    cols: 11,
    rows: 11,
    state: 'thinking',
    poster: [0, 0, 257, 171, 16, 384, 400, 0, 0, 32, 32],
    recipes: ['particles'],
  },
  'spiral-wave': {
    group: 'demoscene',
    cols: 11,
    rows: 11,
    state: 'thinking',
    poster: [112, 268, 516, 2, 242, 178, 130, 132, 120, 0, 0],
    recipes: ['cross', 'shader'],
  },
  sandplate: {
    group: 'demoscene',
    cols: 11,
    rows: 11,
    state: 'thinking',
    poster: [260, 65, 132, 16, 240, 763, 1300, 1152, 1392, 133, 321],
    recipes: ['resolve'],
  },
  'vector-balls': {
    group: 'demoscene',
    cols: 16,
    rows: 16,
    state: 'thinking',
    poster: [0, 0, 0, 0, 0, 5288, 16386, 49155, 49155, 12300, 12684, 384, 0, 0, 0, 0],
    recipes: ['projection'],
  },
  'maze-solve': {
    group: 'emergence',
    cols: 9,
    rows: 9,
    state: 'thinking',
    poster: [0, 224, 0, 0, 0, 0, 0, 0, 0],
    recipes: ['grow'],
  },
  'sort-pass': {
    group: 'emergence',
    cols: 8,
    rows: 8,
    state: 'thinking',
    poster: [64, 72, 73, 105, 107, 123, 251, 255],
    recipes: ['columns'],
  },
  'rule-stream': {
    group: 'emergence',
    cols: 16,
    rows: 9,
    state: 'thinking',
    poster: [0, 0, 0, 0, 0, 0, 0, 0, 128],
    recipes: ['automaton'],
  },
  'flood-search': {
    group: 'emergence',
    cols: 9,
    rows: 9,
    state: 'thinking',
    poster: [0, 128, 28, 0, 14, 64, 64, 64, 0],
    recipes: ['grow'],
  },
  'ant-rewind': {
    group: 'emergence',
    cols: 11,
    rows: 11,
    state: 'thinking',
    poster: [0, 0, 0, 0, 0, 32, 0, 0, 0, 0, 0],
    recipes: ['automaton'],
  },
  'turing-spots': {
    group: 'emergence',
    cols: 16,
    rows: 16,
    state: 'thinking',
    poster: [0, 0, 0, 0, 0, 0, 896, 896, 448, 448, 0, 0, 0, 0, 0, 0],
    recipes: ['automaton'],
  },
  frost: {
    group: 'emergence',
    cols: 11,
    rows: 11,
    state: 'thinking',
    poster: [0, 0, 0, 0, 0, 32, 0, 0, 0, 0, 0],
    recipes: ['grow'],
  },
  fireflies: {
    group: 'emergence',
    cols: 10,
    rows: 10,
    state: 'thinking',
    poster: [0, 0, 0, 0, 512, 0, 0, 0, 0, 0],
    recipes: ['particles'],
  },
  campfire: {
    group: 'nature',
    cols: 8,
    rows: 8,
    state: 'thinking',
    poster: [0, 0, 0, 0, 60, 254, 254, 255],
    recipes: ['automaton'],
  },
  fireworks: {
    group: 'nature',
    cols: 11,
    rows: 11,
    state: 'thinking',
    poster: [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 32],
    recipes: ['particles'],
  },
  fountain: {
    group: 'nature',
    cols: 11,
    rows: 11,
    state: 'thinking',
    poster: [0, 0, 0, 0, 80, 96, 168, 292, 288, 292, 2047],
    recipes: ['particles'],
  },
  'pendulum-wave': {
    group: 'nature',
    cols: 12,
    rows: 7,
    state: 'thinking',
    poster: [0, 0, 0, 0, 0, 0, 4095],
    recipes: ['columns'],
  },
  cradle: {
    group: 'nature',
    cols: 9,
    rows: 4,
    state: 'thinking',
    poster: [0, 0, 2, 120],
    recipes: ['columns'],
  },
  hourglass: {
    group: 'nature',
    cols: 9,
    rows: 11,
    state: 'thinking',
    poster: [0, 254, 124, 56, 16, 0, 0, 0, 0, 0, 0],
    recipes: ['granular'],
  },
  slosh: {
    group: 'nature',
    cols: 9,
    rows: 9,
    state: 'thinking',
    poster: [0, 0, 0, 0, 0, 0, 127, 511, 511],
    recipes: ['columns'],
  },
  droplet: {
    group: 'nature',
    cols: 9,
    rows: 9,
    state: 'thinking',
    poster: [56, 16, 0, 0, 0, 0, 0, 511, 0],
    recipes: ['particles'],
  },
  lightning: {
    group: 'nature',
    cols: 9,
    rows: 13,
    state: 'thinking',
    poster: [32, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
    recipes: ['grow'],
  },
  aurora: {
    group: 'nature',
    cols: 16,
    rows: 9,
    state: 'thinking',
    poster: [26800, 26800, 26800, 26640, 26656, 24592, 0, 16384, 0],
    recipes: ['columns'],
  },
  snowfall: {
    group: 'nature',
    cols: 12,
    rows: 9,
    state: 'thinking',
    poster: [2, 0, 512, 128, 0, 256, 0, 16, 32],
    recipes: ['granular'],
  },
  orrery: {
    group: 'nature',
    cols: 13,
    rows: 13,
    state: 'thinking',
    poster: [0, 0, 208, 0, 0, 0, 64, 0, 96, 0, 0, 0, 0],
    recipes: ['trace'],
  },
  'split-flap': {
    group: 'signboard',
    cols: 9,
    rows: 9,
    state: 'thinking',
    poster: [0, 0, 256, 0, 0, 256, 256, 256, 256],
    recipes: ['resolve'],
  },
  'departure-board': {
    group: 'signboard',
    cols: 16,
    rows: 7,
    state: 'thinking',
    poster: [0, 60134, 35496, 52462, 18468, 20164, 0],
    recipes: ['resolve'],
  },
  decode: {
    group: 'signboard',
    cols: 7,
    rows: 7,
    state: 'thinking',
    poster: [64, 10, 10, 0, 4, 36, 48],
    recipes: ['rain', 'resolve'],
  },
  countdown: {
    group: 'signboard',
    cols: 5,
    rows: 7,
    state: 'thinking',
    poster: [31, 17, 17, 17, 17, 17, 31],
    recipes: ['resolve'],
  },
  'ecg-trace': {
    group: 'signboard',
    cols: 16,
    rows: 7,
    state: 'thinking',
    poster: [256, 256, 256, 4376, 36199, 896, 128],
    recipes: ['columns'],
  },
  scope: {
    group: 'signboard',
    cols: 7,
    rows: 7,
    state: 'thinking',
    poster: [48, 108, 18, 1, 0, 0, 0],
    recipes: ['trace'],
  },
  spirograph: {
    group: 'signboard',
    cols: 9,
    rows: 9,
    state: 'thinking',
    poster: [16, 0, 0, 0, 0, 0, 0, 0, 0],
    recipes: ['trace'],
  },
  cube: {
    group: 'solid',
    cols: 12,
    rows: 12,
    state: 'thinking',
    poster: [0, 1020, 4095, 2049, 1026, 1026, 1026, 1026, 516, 1020, 0, 0],
    recipes: ['projection'],
  },
  globe: {
    group: 'solid',
    cols: 11,
    rows: 11,
    state: 'thinking',
    poster: [248, 292, 682, 1317, 1317, 1317, 1317, 1533, 546, 292, 248],
    recipes: ['projection'],
  },
  donut: {
    group: 'solid',
    cols: 16,
    rows: 16,
    state: 'thinking',
    poster: [0, 2016, 8176, 5456, 16040, 21504, 10248, 20480, 10344, 464, 11232, 320, 0, 0, 0, 0],
    recipes: ['projection'],
  },
  helix: {
    group: 'solid',
    cols: 16,
    rows: 9,
    state: 'thinking',
    poster: [7196, 8738, 1297, 9491, 42130, 25682, 17488, 8738, 7196],
    recipes: ['columns'],
  },
  ridgeline: {
    group: 'solid',
    cols: 16,
    rows: 10,
    state: 'thinking',
    poster: [960, 3104, 4112, 57839, 528, 1036, 63491, 112, 396, 65027],
    recipes: ['columns'],
  },
  'coin-flip': {
    group: 'solid',
    cols: 7,
    rows: 7,
    state: 'thinking',
    poster: [28, 34, 65, 85, 73, 34, 28],
    recipes: ['projection'],
  },
};
