import { frameFromRows } from '../core/codec';
import type { FramesStateDef, IndicatorSet } from '../core/types';
import { BUILTIN, CHECK_STATE, CROSS_STATE, IDLE_STATE } from './shared';

const ADDED_2026_09_29 = '2026-09-29';
const SHIMMER_COLS = 12;
const SHIMMER_ROWS = 3;
const SHIMMER_IDLE_MS = 1000;
const SHIMMER_BAND = 4;

const SHIMMER_IDLE_STATE = {
  kind: 'frames',
  frames: [frameFromRows([0b101010101010, 0b010101010101, 0b101010101010], SHIMMER_COLS)],
  durations: [SHIMMER_IDLE_MS],
} as const satisfies FramesStateDef;

export const THINKING_PRESETS = [
  {
    id: 'pulse',
    name: 'Thinking Pulse',
    description: 'A centre dot that blooms into an eight-point star and settles back, made for AI replies.',
    intent: 'thinking',
    cols: 7,
    rows: 7,
    states: {
      idle: IDLE_STATE,
      thinking: { kind: 'recipe', recipe: 'pulse' },
      success: CHECK_STATE,
      error: CROSS_STATE,
    },
    transition: 'flip',
    tags: ['pulse', 'asterisk', 'chat'],
    contexts: ['chat', 'terminal', 'button', 'card'],
    collections: ['ai'],
    addedAt: '2026-08-19',
    ...BUILTIN,
  },
  {
    id: 'typing-hop',
    name: 'Typing Hop',
    description: 'Three dots that hop up one after another, like someone typing a reply.',
    intent: 'thinking',
    cols: 7,
    rows: 3,
    states: {
      idle: IDLE_STATE,
      thinking: { kind: 'recipe', recipe: 'hop' },
      success: CHECK_STATE,
      error: CROSS_STATE,
    },
    transition: 'cut',
    tags: ['typing', 'chat', 'minimal', 'dots'],
    contexts: ['chat', 'inline', 'button'],
    collections: ['minimal', 'ai'],
    addedAt: ADDED_2026_09_29,
    ...BUILTIN,
  },
  {
    id: 'shimmer',
    name: 'Shimmer',
    description: 'A bright slanted band sweeps across a dim strip, then rests, like a live status label.',
    intent: 'thinking',
    cols: SHIMMER_COLS,
    rows: SHIMMER_ROWS,
    states: {
      idle: SHIMMER_IDLE_STATE,
      thinking: { kind: 'recipe', recipe: 'shimmer', params: { trail: SHIMMER_BAND } },
      success: CHECK_STATE,
      error: CROSS_STATE,
    },
    transition: 'crossfade',
    tags: ['shimmer', 'ai', 'label', 'wide'],
    contexts: ['inline', 'chat', 'button', 'terminal'],
    collections: ['ai'],
    addedAt: ADDED_2026_09_29,
    ...BUILTIN,
  },
  {
    id: 'dots3',
    name: 'Three Dot',
    description: 'The classic three-dot ellipsis, filling in one dot at a time.',
    intent: 'thinking',
    cols: 9,
    rows: 3,
    states: {
      idle: IDLE_STATE,
      thinking: { kind: 'recipe', recipe: 'ellipsis' },
      success: CHECK_STATE,
      error: CROSS_STATE,
    },
    transition: 'cut',
    tags: ['minimal', 'ellipsis', 'chat'],
    contexts: ['chat', 'inline', 'button'],
    collections: ['minimal'],
    addedAt: '2026-07-30',
    ...BUILTIN,
  },
  {
    id: 'ember',
    name: 'Ember Pulse',
    description: 'A compact star that grows from one dot and settles back, sized for inline text.',
    intent: 'thinking',
    cols: 5,
    rows: 5,
    states: {
      idle: IDLE_STATE,
      thinking: { kind: 'recipe', recipe: 'pulse' },
      success: CHECK_STATE,
      error: CROSS_STATE,
    },
    transition: 'crossfade',
    tags: ['pulse', 'star', 'compact'],
    contexts: ['chat', 'inline', 'terminal'],
    collections: ['ai', 'term'],
    addedAt: '2026-09-19',
    ...BUILTIN,
  },
  {
    id: 'radar',
    name: 'Radar',
    description: 'A beam that sweeps around a centre dot, like a radar searching.',
    intent: 'thinking',
    cols: 9,
    rows: 9,
    states: {
      idle: IDLE_STATE,
      thinking: { kind: 'recipe', recipe: 'radar' },
      success: CHECK_STATE,
      error: CROSS_STATE,
    },
    transition: 'flip',
    tags: ['sweep', 'search'],
    contexts: ['page', 'card', 'splash'],
    collections: [],
    addedAt: '2026-08-29',
    ...BUILTIN,
  },
  {
    id: 'breathe',
    name: 'Breathe',
    description: 'A square that slowly grows and shrinks, calm enough for a terminal.',
    intent: 'thinking',
    cols: 5,
    rows: 5,
    states: {
      idle: IDLE_STATE,
      thinking: { kind: 'recipe', recipe: 'breathe' },
      success: CHECK_STATE,
      error: CROSS_STATE,
    },
    transition: 'crossfade',
    tags: ['calm', 'terminal', 'compact'],
    contexts: ['terminal', 'inline', 'button'],
    collections: ['term'],
    addedAt: '2026-08-09',
    ...BUILTIN,
  },
] as const satisfies readonly IndicatorSet[];
